# Generated by Django 2.2 on 2019-05-05 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190505_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['id', '-created_time']},
        ),
    ]
