# Generated by Django 2.2 on 2019-05-05 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20190505_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['id', 'created_time']},
        ),
    ]
